sudo: false
language: python
python: 3.8.5
env:
- CODACY_PROJECT_TOKEN=268cf68dda144158a111126e1c7983b1
install:
- pip install -r requirements.txt
script: coverage run -m pytest
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ls
  - bash <(curl -Ls https://coverage.codacy.com/get.sh)
deploy:
  provider: heroku
  api_key: 8c55cc26-9ec7-4dcc-825a-fbb879174dff
  app: short-url-stage
notifications:
  email:
    on_success: never
    on_failure: always