sudo: false
language: python
python: 3.8.5
env:
- CODACY_PROJECT_TOKEN=268cf68dda144158a111126e1c7983b1
install:
- pip install -r requirements.txt
script: coverage run -m pytest
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ls
  - bash <(curl -Ls https://coverage.codacy.com/get.sh)
before_deploy:
  - export APP_SETTINGS="services.psql_config.ProductionConfig"
  - export DB_URI="postgres://matmpjebyotaps:f1345cc87a16c056b0fde15dd84e7ac729e32b85f08e88c8537d0999a17f055c@ec2-34-237-89-96.compute-1.amazonaws.com:5432/d3hf8as4n7u9a9"
deploy:
  provider: heroku
  api_key: 8c55cc26-9ec7-4dcc-825a-fbb879174dff
  app: short-url-stage
notifications:
  email:
    on_success: never
    on_failure: always