sudo: false
language: python
python: 3.8.5
install:
- pip install -r requirements.txt
script: pytest
deploy:
  provider: heroku
  api_key: 3108a2ec-278f-4853-9df1-e8eb640dba79
  app:
    stage: short-url-stage
  on:
    all_branches: true
